### ISSUE TITLE
Add Travis-CI support

### ISSUE THREAD

**Issue by cagryInside** [CUTR-at-USF/open311-client#4]

**Comment by cagryInside** [comment]
@barbeau Could you please enable `Travis CI` for this project? I don't have admin rights for `CUTR-at-USF` repo in travis.

**Comment by barbeau** [comment]
@cagryInside All set, just enabled it.

Also, could you change the Travis config to the container-based build and Maven caching?

See https://github.com/OneBusAway/onebusaway-application-modules/pull/144 for an example.  It speeds up builds over the legacy config.  I've been trying to change projects over to the new environment as we configure them.

**Comment by cagryInside** [comment]
@barbeau done via https://github.com/CUTR-at-USF/open311-client/commit/2d328e3843b618118d434871d617f923f91581f4. Thanks
