### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by cagryInside** [CUTR-at-USF/open311-client#5]
Travis is failing during the tests.

```
Error logs:

  testOpen311GetServiceList(edu.usf.cutr.open311client.Open311Test): org/json/JSONException : Unsupported major.minor version 52.0

  testPostServiceRequest(edu.usf.cutr.open311client.Open311Test): org/json/JSONException : Unsupported major.minor version 52.0

  testOpen311GetServiceDescription(edu.usf.cutr.open311client.Open311Test): org/json/JSONException : Unsupported major.minor version 52.0

```

More logs:
https://gist.github.com/cagryInside/8708c111e2e848a4f573

Travis fail link:
https://travis-ci.org/CUTR-at-USF/open311-client/builds/80686331

**Comment by barbeau** [comment]
@cagryInside Could you add a link to the failing Travis test too?

**Comment by cagryInside** [comment]
> @cagryInside Could you add a link to the failing Travis test too?

Added.

**Comment by barbeau** [comment]
I think this is related to the version of Java that Travis is running, versus your local machine.  Can you try changing the Travis Java version and see if it works?

See http://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs.

**Comment by cagryInside** [comment]
Using the jdk `oraclejdk8` fixed the problem in travis.
@barbeau thanks.

**Comment by barbeau** [comment]
Thanks @cagryInside!
